# Minecraft
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.1
loader_version=0.15.7

# Fabric API (VERSI YANG ADA & STABIL)
fabric_version=0.99.4+1.21

# Fabric Loom
loom_version=1.6.12

# Mod info
mod_version=1.0.0
maven_group=com.tnt.autoplayer
archives_base_name=tnt-autoplayer

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
